### PR TITLE
Update to 1.15.2

### PR DESCRIPTION
**Pull request by arollyson**
Updated the mod to be 1.15.2 compatible. Some notes since there was some pretty significant changes:

- Cleaned up the gradle build environment stuff to be in line with the standard setups you see in the Forge examples
- Updated the pack metadata (META-INF/mods.tml, etc)
- Removed most of the Quark boilerplate since it would have all needed updated as well
- With the Quark boilerplate removed, simplified the mod into just a main mod file and a config handler file

Hopefully that all makes sense. I apologize for the big refactor, it was easier to rip out most of it and start fresh than to update all the boilerplate stuff.

### CODE REVIEW

**Comment by spradlin-dev** [comment]
Unfortunately I have lost access to the JaSpr GitHub account.  Lost my phone, which had my 2FA on it, and could never find the recovery keys.

**Comment by arollyson** [comment]
Aww man, well that sucks. How do you want to handle the update then? It's your mod, so whatever you want to do works for me.

**Comment by spradlin-dev** [comment]
I can fork it on my new account (this one), and have that be the main repo.  Just not tonight.

**Comment by arollyson** [comment]
Resurrecting this as I was looking at updating again to 1.16+, what are your thoughts? If you don't want to mess with another repo, you could just add me as a member to the curseforge mod page so I can upload newer versions from my fork. Really whatever you want to do.

**Comment by spradlin-dev** [comment]
What's your curseforge username?

**Comment by arollyson** [comment]
forkbomb_

**Pull request closed without merging**
